=== shangyuk/Music-Store-Page/Music Store/catalog_19031649.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> <!--schema is declared-->
	<!--schema for root element 'musicStore'-->
	<xs:element name="musicStore">
		<xs:complexType>
			<xs:sequence><!--compositor type-->
				<!--schema for element 'storeDetails'-->
				<xs:element name="storeDetails">
					<xs:complexType>
						<xs:sequence>
							<!--schema for element 'logo'-->
							<xs:element name="logo">
								<xs:simpleType>
									<!--'logo' element is restricted to contain no data-->
						            <xs:restriction base="xs:string">
						            	<xs:length value="0"/>
						            </xs:restriction>
					         	</xs:simpleType>
					        </xs:element>
							<!--simpleType tag are self closing tag-->
							<xs:element name="storeName" type="xs:string" /><!--schema for element 'storeName'-->
							<xs:element name="address" type="xs:string" /><!--schema for element 'address'-->
							<xs:element name="phoneNum" type="xs:string" /><!--schema for element 'phoneNum'-->
							<xs:element name="website" type="xs:string" /><!--schema for element 'website'-->
						</xs:sequence>
						<!--attribute for element 'storeDetails' is set-->
						<xs:attribute name="storeID" type="xs:ID" use="required"/>
					</xs:complexType>
				</xs:element>
				<!--schema for element 'inventory'-->
				<xs:element name="inventory">
					<xs:complexType>
						<xs:sequence>
							<!--schema for element 'album' allowing it to occur more than once-->
							<xs:element name="album" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="albumTitle" type="xs:string" /><!--schema for element 'albumTitle'-->
										<!--schema for element 'albumArt'-->
										<xs:element name="albumArt">
											<xs:simpleType>
												<!--'albumArt' element is restricted to contain no data-->
									            <xs:restriction base="xs:string">
									                <xs:length value="0"/>
									            </xs:restriction>
									        </xs:simpleType>
									    </xs:element>
									    <!--schema for element 'songs'-->
										<xs:element name="songs">
											<xs:complexType>
												<xs:sequence>
													<!--schema for element 'song' allowing it to occur more than once-->
													<xs:element name="song" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="songName" type="xs:string"/><!--schema for element 'songName'-->
																<xs:element name="genre" type="xs:string"/><!--schema for element 'genre'-->
																<xs:element name="director" type="xs:string" minOccurs="0"/><!--schema for optional element 'director'-->
																<xs:element name="producers">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="producer" type="xs:string" minOccurs="1" maxOccurs="unbounded"/><!--schema for element 'producer' allowing it to occur more than once-->
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="writers">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="writer" type="xs:string" minOccurs="1" maxOccurs="unbounded"/><!--schema for element 'writer' allowing it to occur more than once-->
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="singer" type="xs:string"/><!--schema for element 'singer'-->
																<xs:element name="featuredArtist" type="xs:string" minOccurs="0"/><!--schema for optional element 'featuredArtist'-->
																<!--schema for element 'releaseDate'-->
																<xs:element name="releaseDate">
																	<xs:complexType>
																		<xs:sequence>
																			<!--schema for optional element 'day'-->
																			<xs:element name="day" minOccurs="0">
																				<xs:simpleType>
																					<!--restriction for day is set-->
																					<xs:restriction base="xs:integer">
																						<xs:pattern value="[0-3][0-9]"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:element name="month" type="xs:string" minOccurs="0"/><!--schema for optional element 'month'-->
																			<!--schema for element 'year'-->
																			<xs:element name="year">
																				<xs:simpleType>
																					<!--restriction for year is set-->
																					<xs:restriction base="xs:integer">
																						<xs:pattern value="[0-9]{4}"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="label" type="xs:string" minOccurs="0"/><!--schema for optional element 'label'-->
																<xs:element name="price" type="xs:positiveInteger"/><!--schema for element 'price'-->
															</xs:sequence>
															<!--attributes for element 'song' are set-->
															<xs:attribute name="songID" type="xs:ID" use="required"/>
															<xs:attribute name="length" type="xs:time" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<!--attributes for element 'album' are set-->
									<xs:attribute name="albumID" type="xs:ID" use="required"/>
									<xs:attribute name="category" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== shangyuk/Music-Store-Page/Music Store/catalog_19031649.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--CSS stylesheet is linked-->
<?xml-stylesheet type="text/css" href="catalog_19031649.css"?>
<!--Root element musicStore is created and external schema is linked-->
<musicStore xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
		xs:noNamespaceSchemaLocation="catalog_19031649.xsd">
		<!--storeDetails element storing details of the music store is created-->
		<storeDetails storeID="A015389KTM"><!--opening tag-->
			<logo></logo>
			<storeName>Pandora Records</storeName>
			<address>Kathmandu, Nepal</address>
			<phoneNum>9803456215</phoneNum>
			<website>www.pandorarecords.com</website>
		</storeDetails><!--closing tag-->
		<!--inventory element containing multiple album is created-->
		<inventory>
			<!--album element, containing albumTitle, albumArt and songs is created-->
			<album albumID="W34" category="Pop">
				<albumTitle>Whenever You Need Somebody</albumTitle>
				<albumArt></albumArt>
				<!--songs element containing multiple song is created-->
				<songs>
					<!--song element containing song details is created-->
					<song songID="W34T01" length="00:03:35">
						<songName>Never Gonna Give You Up</songName>
						<genre>Dance-pop</genre>
						<director>Simon West</director>
						<producers>
							<producer>Stock Aitken Waterman</producer>
						</producers>
						<writers>
							<writer>Mike Stock</writer>
							<writer>Matt Aitken</writer>
							<writer>Pete Waterman</writer>
						</writers>
						<singer>Rick Astley</singer>
						<releaseDate>
							<day>27</day>
							<month>July</month>
							<year>1987</year>
						</releaseDate>
						<label>RCA</label>
						<price>690</price>
					</song>
					<!--song element containing song details is created-->
					<song songID="W34T07" length="00:03:52">
						<songName>Slipping Away</songName>
						<genre>Pop</genre>
						<producers>
							<producer>Phil Harding</producer>
							<producer>Ian Curnow</producer>
						</producers>
						<writers>
							<writer>Rick Astley</writer>
						</writers>
						<singer>Rick Astley</singer>
						<releaseDate>
							<year>1987</year>
						</releaseDate>
						<label>RCA</label>
						<price>600</price>
					</song>
				</songs>
			</album>
			<!--album element, containing albumTitle, albumArt and songs is created-->
			<album albumID="P07" category="Comedy Hip Hop">
				<albumTitle>Pink Season</albumTitle>
				<albumArt></albumArt>
				<!--songs element containing multiple song is created-->
				<songs>
					<!--song element containing song details is created-->
					<song songID="P07T21" length="00:02:24">
						<songName>Dora the Explora</songName>
						<genre>Hip hop</genre>
						<producers>
							<producer>Pink Guy</producer>
						</producers>
						<writers>
							<writer>Pink Guy</writer>
						</writers>
						<singer>Pink Guy</singer>
						<releaseDate>
							<day>04</day>
							<month>January</month>
							<year>2017</year>
						</releaseDate>
						<price>420</price>
					</song>
					<!--song element containing song details is created-->
					<song songID="P07T29" length="00:03:10">
						<songName>Pink Life</songName>
						<genre>Hip hop</genre>
						<producers>
							<producer>Holder</producer>
						</producers>
						<writers>
							<writer>Pink Guy</writer>
						</writers>
						<singer>Pink Guy</singer>
						<releaseDate>
							<day>04</day>
							<month>January</month>
							<year>2017</year>
						</releaseDate>
						<price>420</price>
					</song>
				</songs>
			</album>
			<!--album element, containing albumTitle, albumArt and songs is created-->
			<album albumID="N18" category="Rhythem and Blues">
				<albumTitle>Nine Track Mind</albumTitle>
				<albumArt></albumArt>
				<!--songs element containing multiple song is created-->
				<songs>
					<!--song element containing song details is created-->
					<song songID="N18T13" length="00:03:49">
						<songName>See You Again</songName>
						<genre>Pop-rap</genre>
						<director>Marc Klasfeld</director>
						<producers>
							<producer>DJ Frank E</producer>
							<producer>Charlie Puth</producer>
							<producer>Andrew Cedar</producer>
						</producers>
						<writers>
							<writer>Charlie Puth</writer>
							<writer>Justin Franks</writer>
							<writer>Andrew Cedar</writer>
							<writer>Cameron Jibril Thomaz</writer>
						</writers>
						<singer>Wiz Khalifa</singer>
						<featuredArtist>Charlie Puth</featuredArtist>
						<releaseDate>
							<day>10</day>
							<month>March</month>
							<year>2015</year>
						</releaseDate>
						<label>Atlantic</label>
						<price>500</price>
					</song>
					<!--song element containing song details is created-->
					<song songID="N18T06" length="00:03:30">
						<songName>My Gospel</songName>
						<genre>Pop</genre>
						<producers>
							<producer>Charlie Puth</producer>
						</producers>
						<writers>
							<writer>Charlie Puth</writer>
							<writer>Josh Kear</writer>
						</writers>
						<singer>Charlie Puth</singer>
						<releaseDate>
							<day>29</day>
							<month>January</month>
							<year>2016</year>
						</releaseDate>
						<label>Atlantic</label>
						<price>480</price>
					</song>
				</songs>
			</album>
		</inventory>
</musicStore>
